delete science_prefixes.txt
delete extracted_speclist.txt
delete first_spectrum.txt
delete arc_prefixes.txt
delete run*.ms.fits
delete first_wavecal.fits
delete masterarc.fits
delete database/aplast
delete database/aprun*.a*
delete database/apmasterarc_straight
delete full_disp_list.txt
delete run*.ms.d.fits
delete *straight*.fits
delete masterarc_straight.fits
delete shifted_arc.fits
delete mastershifts.txt
delete masterRefSpec.sav
delete masterArcList.txt
delete straight_masterarcList.txt
